version: '3'
services:
  api:
    image: api-fashion
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:80
  frontend:
    image: fontend-ropa
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8082:80
    depends_on:
      - api